### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by marianomd** [hackocopter/JD385_Documentation#1]
Hello! I'm porting Bradwii to UDI U842 board, and I can't tell what are the MOTOR SENSE pins for. It seems that in JD385 are not populated. Maybe you can help me out with this. The sense pin is depicted here as P1.0 (ACMP0_P/AIN1) What should it sense?

![IMG_20201203_155542](https://user-images.githubusercontent.com/274989/101077014-f2c5c500-3582-11eb-965a-1185fe92edb9.jpg)

**Comment by victzh** [comment]
It is current sense pin to find out is motor blocked or working normally. If motor stalls the current consumption raises and the voltage drop on sense resistor (in your schematics - two 0.01 resistors connected in parallel) can be sensed by MCU. It is optional and prevents motor burn out in case of crash.

**Comment by marianomd** [comment]
Thank you very much for your response, I'm some years late to the party, but enjoying very much and learning to program MCUs in one shot.

I will try to implement it, the problem is that when i turn on ADC, at least for voltage sensing, it seems SPI stops working (4 wire, not the software one). It seems to be some issue with the clock.

You did a terrific job!!! Thanks!!
